name: benchmark_gnn
channels:
- conda-forge
- defaults
dependencies:
- python==3.7
- pip
- pip:
  - absl-py==0.10.0
  - albumentations==0.4.6
  - ase==3.20.1
  - astor==0.8.1
  - cachetools==4.1.1
  - chardet==3.0.4
  - click==7.0
  - cycler==0.10.0
  - dgl==0.5.2
  - efficientnet-pytorch==0.6.3
  - future==0.18.2
  - gast==0.2.2
  - google-auth==1.21.2
  - google-auth-oauthlib==0.4.1
  - google-pasta==0.2.0
  - googledrivedownloader==0.4
  - grpcio==1.32.0
  - h5py==2.10.0
  - idna==2.8
  - imageio==2.9.0
  - imgaug==0.4.0
  - isodate==0.6.0
  - jsonpatch==1.26
  - jsonpointer==2.0
  - keras-applications==1.0.8
  - keras-preprocessing==1.1.2
  - kiwisolver==1.2.0
  - littleutils==0.2.2
  - logger==1.4
  - loguru==0.5.1
  - markdown==3.2.2
  - matplotlib==3.3.0
  - mkl==2019.0  # next version 2021.1.1
  - numpy==1.19.2
  - oauthlib==3.1.0
  - ogb==1.2.6
  - opencv-python==4.3.0.38
  - opencv-python-headless==4.3.0.38
  - opt-einsum==3.3.0
  - outdated==0.2.0
  - pandas==1.1.0
  - pillow==7.2.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pycls==0.0.0
  - pywavelets==1.1.1
  - python-dateutil==2.8.0
  - rdflib==5.0.0
  - requests==2.22.0
  - requests-oauthlib==1.3.0
  - rsa==4.6
  - scikit-image==0.17.2
  - scikit-learn==0.23.2
  - scipy==1.4.1
  - seaborn==0.10.1
  - shapely==1.7.0
  - sotabenchapi==0.0.16
  - tabulate==0.8.3
  - tensorboard==2.1.1
  - tensorboardx==2.5.1
  - tensorflow-estimator==2.1.0
  - tensorflow-gpu==2.1.0
  - termcolor==1.1.0
  - tifffile==2020.7.24
  - timm==0.1.30
  - torch==1.6.0
  # - torch-cluster==1.5.7
  - torch-geometric==1.6.1
  # - torch-scatter==2.0.5
  # - torch-sparse==0.6.7
  # - torch-spline-conv==1.2.0
  # - torchbench==0.0.31
  # - torchfile==0.1.0
  - torchvision==0.7.0
  - urllib3==1.25.10
  - visdom==0.1.8.9
  - websocket-client==0.57.0
  - werkzeug==1.0.1
